# -*- coding: utf-8 -*-
"""AssistV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fDvICg41seGk5qovyz-tcmj6G_Lel-f5
"""

!pip install SpeechRecognition

!pip install geopy

!pip install SpeechRecognition geopy pyttsx3

# import speech_recognition as sr
import webbrowser
from geopy.geocoders import Nominatim

# Função para simular o reconhecimento de fala (implementação real requer bibliotecas adicionais)
def reconhecer_comando():
    return input("Digite o comando de voz: ").lower()

# Função para abrir pesquisa no Wikipedia (não implementada neste exemplo)
def abrir_pesquisa_wikipedia():
    print("Função para abrir pesquisa no Wikipedia ainda não implementada.")

# Função para abrir o Youtube
def abrir_youtube():
    webbrowser.open("https://www.youtube.com/")

# Função para localizar farmácia mais próxima
def localizar_farmacia_proxima():
    geolocator = Nominatim(user_agent="localizador_farmacia")
    localizacao = geolocator.geocode("farmacia", language="pt")
    if localizacao:
        latitude, longitude = localizacao.latitude, localizacao.longitude
        url = f"https://www.google.com/maps/search/farmacia/@{latitude},{longitude}"
        webbrowser.open(url)
    else:
        print("Não foi possível encontrar a localização da farmácia mais próxima.")

if __name__ == "__main__":
    while True:
        print("O que você quer fazer?")
        comando = reconhecer_comando()

        if "abrir pesquisa no wikipedia" in comando:
            abrir_pesquisa_wikipedia()

        elif "abrir o youtube" in comando:
            abrir_youtube()

        elif "apresentar a localização da farmácia mais próxima" in comando:
            localizar_farmacia_proxima()

        elif "sair" in comando:
            print("Encerrando o programa...")
            break

        else:
            print("Comando não reconhecido. Tente novamente.")

import speech_recognition as sr
import webbrowser
from geopy.geocoders import Nominatim

def reconhecer_comando():
    recognizer = sr.Recognizer()

    with sr.Microphone() as source:
        print("Diga algo...")
        audio = recognizer.listen(source)

    try:
        texto = recognizer.recognize_google(audio, language="pt-BR")
        print("Você disse: " + texto)
        return texto.lower()
    except sr.UnknownValueError:
        print("Não consegui entender o áudio.")
    except sr.RequestError as e:
        print("Erro ao chamar a API do Google; {0}".format(e))

    return None

def abrir_pesquisa_wikipedia():
    # (código de abrir pesquisa no Wikipedia como antes)

def abrir_youtube():
    pass

def localizar_farmacia_proxima():
    # (código de localizar farmácia mais próxima como antes)

if __name__ == "__main__":
    while True:
        print("O que você quer fazer?")
        comando = reconhecer_comando()

        if "abrir pesquisa no wikipedia" in comando:
            abrir_pesquisa_wikipedia()

        elif "abrir o youtube" in comando:
            abrir_youtube()

        elif "apresentar a localização da farmácia mais próxima" in comando:
            localizar_farmacia_proxima()

        elif "sair" in comando:
            print("Encerrando o programa...")
            break

        else:
            print("Comando não reconhecido. Tente novamente.")

import speech_recognition as sr
import webbrowser
from geopy.geocoders import Nominatim

def reconhecer_comando():
    recognizer = sr.Recognizer()

    with sr.Microphone() as source:
        print("Diga algo...")
        audio = recognizer.listen(source)

    try:
        texto = recognizer.recognize_google(audio, language="pt-BR")
        print("Você disse: " + texto)
        return texto.lower()
    except sr.UnknownValueError:
        print("Não consegui entender o áudio.")
    except sr.RequestError as e:
        print("Erro ao chamar a API do Google; {0}".format(e))

    return None

def abrir_pesquisa_wikipedia():
    comando = reconhecer_comando()
    if comando:
        pesquisa = comando.replace("abrir pesquisa no wikipedia", "")
        pesquisa = pesquisa.strip()
        url = "https://pt.wikipedia.org/wiki/" + pesquisa
        webbrowser.open(url)

def abrir_youtube():
    webbrowser.open("https://www.youtube.com/")

def localizar_farmacia_proxima():
    geolocator = Nominatim(user_agent="localizador_farmacia")
    localizacao = geolocator.geocode("farmacia", language="pt")
    if localizacao:
        latitude, longitude = localizacao.latitude, localizacao.longitude
        url = f"https://www.google.com/maps/search/farmacia/@{latitude},{longitude}"
        webbrowser.open(url)
    else:
        print("Não foi possível encontrar a localização da farmácia mais próxima.")

if __name__ == "__main__":
    while True:
        print("O que você quer fazer?")
        comando = reconhecer_comando()

        if "abrir pesquisa no wikipedia" in comando:
            abrir_pesquisa_wikipedia()

        elif "abrir o youtube" in comando:
            abrir_youtube()

        elif "apresentar a localização da farmácia mais próxima" in comando:
            localizar_farmacia_proxima()

        elif "sair" in comando:
            print("Encerrando o programa...")
            break

        else:
            print("Comando não reconhecido. Tente novamente.")